spring:
  datasource:
    master: #C端edu数据库
      url: jdbc:mysql://localhost:3306/mt-shop?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 123456
      driver-class-name: com.mysql.cj.jdbc.Driver #mysql低版本的请用com.mysql.jdbc.Driver，我这个是高版本
    slave: #B端ops数据库
      url: jdbc:mysql://localhost:3306/mt-order?allowMultiQueries=true&useUnicode=true&characterEncoding=utf-8&useSSL=false
      username: root
      password: 999999
      driver-class-name: com.mysql.cj.jdbc.Driver #mysql低版本的请用com.mysql.jdbc.Driver，我这个是高版本
    druid:
      initial-size: 5 #连接池初始化大小
      min-idle: 10 #最小空闲连接数
      max-active: 20 #最大连接数
      max-wait: 10000
      time-between-eviction-runs-millis: 10000
      min-evictable-idle-time-millis: 1800000
      validation-query: select 'x'
      test-while-idle: true
      test-on-return: false
      test-on-borrow: false
      pool-prepared-statements: true
      max-open-prepared-statements: 20
      filters: stat